# STATE MACHINE
# ========================= STATES ==========================
start_state = 'start_state'
end_state = 'end_state'
lane_following = 'lane_following'
classifying_sign = 'classifying_sign'
stop_state = 'stop_state'
parking_state = 'parking_state'
waiting_for_pedestrian = 'waiting_for_pedestrian'
overtaking_moving_car = 'overtaking_moving_car'
overtaking_static_car = 'overtaking_static_car'
avoiding_roadblock = 'avoiding_roadblock'
classifying_obstacle = 'classifying_obstacle'
tailing_car = 'tailing_car'
approaching_stop_line = 'approaching_stop_line'
crosswalk_navigation = 'crosswalk_navigation'
roundabout_navigation = 'roundabout_navigation'
tracking_local_path = 'tracking_local_path'
intersection_navigation = 'intersection_navigation'
waiting_at_stopline = 'waiting_at_stopline'
waiting_for_green = 'waiting_for_green'
highway_state = 'highway_state'
crosswalk_state = 'crosswalk_state'
priority_state = 'priority_state'
traffic_light_state = 'traffic_light_state'
red_state = 'red_state'
yellow_state = 'yellow_state'
stopline_state = 'stopline_state'
pedestrian_crossing = 'pedestrian_crossing'
continue_line = 'continue_line'
# ======================== ROUTINES =========================
control_for_signs = 'control_for_signs'

# ========================= EVENTS ==========================
ROADMAP_LOADED = 'ROADMAP_LOADED'
OBSTACLE_DISTANCE_THRESHOLD = 'OBSTACLE_DISTANCE_THRESHOLD'
SIGN_DISTANCE_THRESHOLD = 'SIGN_DISTANCE_THRESHOLD'
END_EVENT = 'END_EVENT'
STOP_LINE_APPROACH_DISTANCE_THRESHOLD = 'STOP_LINE_APPROACH_DISTANCE_THRESHOLD'
PARKING_SIGN_DETECTED = 'PARKING_SIGN_DETECTED'
TRY_PARKING = 'TRY_PARKING'
CONTINUE_LANE_FOLLOWING = 'CONTINUE_LANE_FOLLOWING'
STOP_SIGN_DETECTED = 'STOP_SIGN_DETECTED'
TIMEOUT_STOP = 'TIMEOUT_STOP'
PARKING_COMPLETED = 'PARKING_COMPLETED'
PEDESTRIAN_TIMEOUT = 'PEDESTRIAN_TIMEOUT'
CAR_OVERTAKEN = 'CAR_OVERTAKEN'
ROADBLOCK_AVOIDED = 'ROADBLOCK_AVOIDED'
OBSTACLE_PEDESTRIAN = 'OBSTACLE=PEDESTRIAN'
OBSTACLE_CAR = 'OBSTACLE=CAR'
OBSTACLE_ROADBLOCK = 'OBSTACLE=ROADBLOCK'
IF_OBSTACLE_TOO_FAR = 'IF_OBSTACLE_TOO_FAR'
IF_MOVING = 'IF_MOVING'
IF_STATIC = 'IF_STATIC'
CROSSWALK_SIGN_DETECTED = 'CROSSWALK_SIGN_DETECTED'
TIMEOUT_CROSSWALK = 'TIMEOUT_CROSSWALK'
INTERSECTION_TRAFFIC_LIGHT_EVENT = 'INTERSECTION_TRAFFIC_LIGHT_EVENT'
INTERSECTION_STOP_EVENT = 'INTERSECTION_STOP_EVENT'
JUNCTION_EVENT = 'JUNCTION_EVENT'
INTERSECTION_PRIORITY_EVENT = 'INTERSECTION_PRIORITY_EVENT'
ROUNDABOUT_EVENT = 'ROUNDABOUT_EVENT'
ALWAYS = 'ALWAYS'
END_OF_LOCAL_PATH = 'END_OF_LOCAL_PATH'
TIMEOUT_STOPLINE = 'TIMEOUT_STOPLINE'
SEMAPHORE_GREEN = 'SEMAPHORE_GREEN'
WAITING_STOP = 'WAITING_STOP'
HIGHWAY_ENTRY_SIGN_DETECTED = 'HIGHWAY_ENTRY_SIGN_DETECTED'
IN_HIGHWAY = 'IN HIGHWAY'
HIGHWAY_END_SIGN_DETECTED = 'HIGHWAY_END_SIGN_DETECTED'

PRIORITY_SIGN_DETECTED = 'PRIORITY_SIGN_DETECTED'
ONE_WAY_SIGN_DETECTED = 'ONE_WAY_SIGN_DETECTED'
ROUNDABOUT_SIGN_DETECTED = 'ROUNDABOUT_SIGN_DETECTED'
NO_ENTRY_SIGN_DETECTED = 'NO_ENTRY_SIGN_DETECTED'
PEDESTRIAN_DETECTED = 'PEDESTRIAN_DETECTED'
CAR_DETECTED = 'CAR_DETECTED'
ROADBLOCK_DETECTED = 'ROADBLOCK_DETECTED'
TRACKING_NODE = 'TRACKING_NODE'
FINAL_NODE_REACHED = 'FINAL_NODE_REACHED'

CROSSWALK_TIMEOUT = 'CROSSWALK_TIMEOUT'
WAITING_CROSSWALK = 'WAITING_CROSSWALK'

PRIORITY_INTERSECTION = 'PRIORITY_INTERSECTION'

RED_LIGHT_DETECTED = 'RED_LIGHT_DETECTED'
YELLOW_LIGHT_DETECTED = 'YELLOW_LIGHT_DETECTED'
RED_LIGHT_FINISHED = 'RED_LIGHT_FINISHED'
WAITING_RED_LIGHT = 'WAITING_RED_LIGHT'
WAITING_YELLOW_LIGHT = 'WAITING_YELLOW_LIGHT'
YELLOW_LIGHT_FINISHED = 'YELLOW_LIGHT_FINISHED'
GREEN_LIGHT_DETECTED = 'GREEN_LIGHT_DETECTED'

WAITING_STOPLINE = 'WAITING_STOPLINE'


WAITING_PEDESTRIAN = 'WAITING_PEDESTRIAN'
PEDESTRIAN_CROSSED = 'PEDESTRIAN_CROSSED'

TRY_AVOID_ROADBLOCK = 'TRY_AVOID_ROADBLOCK'
IF_CONTINUE_LINE = 'IF_CONTINUE_LINE'
WAITING_OBSTACLE = 'WAITING_OBSTACLE'
OBSTACLE_GONE = 'OBSTACLE_GONE'

EVENT_TYPES = [
    ROADMAP_LOADED, OBSTACLE_DISTANCE_THRESHOLD, SIGN_DISTANCE_THRESHOLD, END_EVENT,
    STOP_LINE_APPROACH_DISTANCE_THRESHOLD, PARKING_SIGN_DETECTED, TRY_PARKING, CONTINUE_LANE_FOLLOWING,
    STOP_SIGN_DETECTED, WAITING_STOP, TIMEOUT_STOP, PARKING_COMPLETED, PEDESTRIAN_TIMEOUT, CAR_OVERTAKEN,
    ROADBLOCK_AVOIDED, OBSTACLE_PEDESTRIAN, OBSTACLE_CAR, OBSTACLE_ROADBLOCK, IF_OBSTACLE_TOO_FAR,
    IF_MOVING, IF_STATIC, CROSSWALK_SIGN_DETECTED, TIMEOUT_CROSSWALK, INTERSECTION_TRAFFIC_LIGHT_EVENT,
    INTERSECTION_STOP_EVENT, JUNCTION_EVENT, INTERSECTION_PRIORITY_EVENT, ROUNDABOUT_EVENT,
    ALWAYS, END_OF_LOCAL_PATH, TIMEOUT_STOPLINE, SEMAPHORE_GREEN, HIGHWAY_ENTRY_SIGN_DETECTED, IN_HIGHWAY, PRIORITY_SIGN_DETECTED,
    ONE_WAY_SIGN_DETECTED,ROUNDABOUT_SIGN_DETECTED, NO_ENTRY_SIGN_DETECTED, PEDESTRIAN_DETECTED,
    CAR_DETECTED, ROADBLOCK_DETECTED, TRACKING_NODE, FINAL_NODE_REACHED,PRIORITY_INTERSECTION,
    CROSSWALK_TIMEOUT, WAITING_CROSSWALK,RED_LIGHT_DETECTED,YELLOW_LIGHT_DETECTED, WAITING_RED_LIGHT, RED_LIGHT_FINISHED, WAITING_YELLOW_LIGHT,
    YELLOW_LIGHT_FINISHED, GREEN_LIGHT_DETECTED, WAITING_STOPLINE, WAITING_PEDESTRIAN, PEDESTRIAN_CROSSED, TRY_AVOID_ROADBLOCK,
    IF_CONTINUE_LINE, OBSTACLE_GONE, WAITING_OBSTACLE,
]

# ========================= SIGNS ==========================
STOP_SIGN = "STOP"
PARKING_SIGN = "PARKING"
CROSSWALK_SIGN = "CROSSWALK"
PRIORITY_SIGN = "PRIORITY"
HIGHWAY_ENTRY_SIGN = "HIGHWAY_ENTRY"
HIGHWAY_END_SIGN = "HIGHWAY_END"
ONE_WAY_SIGN = "ONE_WAY"
ROUNDABOUT_SIGN = "ROUNDABOUT"
NO_ENTRY_SIGN = "NO_ENTRY"

# ========================= OBSTACLES ==========================
PEDESTRIAN = "PEDESTRIAN"
CAR = "CAR"
ROADBLOCK = "ROADBLOCK"
