# STATE MACHINE
# ========================= STATES ==========================
start_state = 'start_state'
end_state = 'end_state'
lane_following = 'lane_following'
classifying_signal = 'classifying_signal'
stop_state = 'stop_state'
parking_state = 'parking_state'
overtaking_moving_car = 'overtaking_moving_car'
overtaking_static_car = 'overtaking_static_car'
avoiding_roadblock = 'avoiding_roadblock'
classifying_obstacle = 'classifying_obstacle'
tailing_car = 'tailing_car'
approaching_stop_line = 'approaching_stop_line'
tracking_local_path = 'tracking_local_path'
highway_state = 'highway_state'
crosswalk_state = 'crosswalk_state'
traffic_light_state = 'traffic_light_state'
red_state = 'red_state'
yellow_state = 'yellow_state'
stopline_state = 'stopline_state'
pedestrian_crossing = 'pedestrian_crossing'
continue_lane = 'continue_lane'
parking_find_slot = 'parking_find_slot'
parking_both_sides_occupied = 'parking_both_sides_occupied'
parking_left_state = 'parking_left_state'
# ======================== ROUTINES =========================
control_for_signs = 'control_for_signs'

# ========================= EVENTS ==========================
ROADMAP_LOADED = 'ROADMAP_LOADED'
END_EVENT = 'END_EVENT'
OBSTACLE_DISTANCE_THRESHOLD = 'OBSTACLE_DISTANCE_THRESHOLD'
SIGNAL_DISTANCE_THRESHOLD = 'SIGNAL_DISTANCE_THRESHOLD'
STOP_LINE_DISTANCE_THRESHOLD = 'STOP_LINE_DISTANCE_THRESHOLD'
STOP_LINE_BLOCKED = 'STOP_LINE_BLOCKED'

PARKING_SIGN_DETECTED = 'PARKING_SIGN_DETECTED'
TRY_PARKING = 'TRY_PARKING'
PARKING_FINDING_SLOT = 'PARKING_FINDING_SLOT'
PARKING_SLOT_FOUND = 'PARKING_SLOT_FOUND'
PARKING_BOTH_SIDES_OCCUPIED = 'PARKING_BOTH_SIDES_OCCUPIED'
PARKING_ADVANCE_WAITING = 'PARKING_ADVANCE_WAITING'
PARKING_SLOT_ADVANCED = 'PARKING_SLOT_ADVANCED'
PARKING_COMPLETED = 'PARKING_COMPLETED'
TRY_LEFT_PARKING = 'TRY_LEFT_PARKING'
CONTINUE_ON_LANE = 'CONTINUE_ON_LANE'

CONTINUE_LANE_FOLLOWING = 'CONTINUE_LANE_FOLLOWING'

STOP_SIGN_DETECTED = 'STOP_SIGN_DETECTED'
STOP_WAITING = 'STOP_WAITING'
STOP_TIMEOUT = 'STOP_TIMEOUT'

PEDESTRIAN_TIMEOUT = 'PEDESTRIAN_TIMEOUT'
CAR_OVERTAKEN = 'CAR_OVERTAKEN'
ROADBLOCK_AVOIDED = 'ROADBLOCK_AVOIDED'
IF_MOVING = 'IF_MOVING'
IF_STATIC = 'IF_STATIC'
CROSSWALK_SIGN_DETECTED = 'CROSSWALK_SIGN_DETECTED'
CROSSWALK_WAITING = 'CROSSWALK_WAITING'
END_OF_LOCAL_PATH = 'END_OF_LOCAL_PATH'
STOPLINE_TIMEOUT = 'STOPLINE_TIMEOUT'
SEMAPHORE_GREEN = 'SEMAPHORE_GREEN'
HIGHWAY_ENTRY_SIGN_DETECTED = 'HIGHWAY_ENTRY_SIGN_DETECTED'
IN_HIGHWAY = 'IN HIGHWAY'
HIGHWAY_END_SIGN_DETECTED = 'HIGHWAY_END_SIGN_DETECTED'

PRIORITY_SIGN_DETECTED = 'PRIORITY_SIGN_DETECTED'
ONE_WAY_SIGN_DETECTED = 'ONE_WAY_SIGN_DETECTED'
ROUNDABOUT_SIGN_DETECTED = 'ROUNDABOUT_SIGN_DETECTED'
NO_ENTRY_SIGN_DETECTED = 'NO_ENTRY_SIGN_DETECTED'
PEDESTRIAN_DETECTED = 'PEDESTRIAN_DETECTED'
CAR_DETECTED = 'CAR_DETECTED'
ROADBLOCK_DETECTED = 'ROADBLOCK_DETECTED'
TRACKING_NODE = 'TRACKING_NODE'
FINAL_NODE_REACHED = 'FINAL_NODE_REACHED'

INTERSECTION_STOP = 'INTERSECTION_STOP'
INTERSECTION_PRIORITY_EVENT = 'INTERSECTION_PRIORITY_EVENT'

CROSSWALK_TIMEOUT = 'CROSSWALK_TIMEOUT'

INTERSECTION_PRIORITY = 'INTERSECTION_PRIORITY'

TRAFFIC_LIGHT_DETECTED = 'TRAFFIC_LIGHT_DETECTED'
RED_LIGHT_DETECTED = 'RED_LIGHT_DETECTED'
RED_LIGHT_WAITING = 'RED_LIGHT_WAITING'
RED_LIGHT_FINISHED = 'RED_LIGHT_FINISHED'
YELLOW_LIGHT_DETECTED = 'YELLOW_LIGHT_DETECTED'
YELLOW_LIGHT_WAITING = 'YELLOW_LIGHT_WAITING'
YELLOW_LIGHT_FINISHED = 'YELLOW_LIGHT_FINISHED'
GREEN_LIGHT_DETECTED = 'GREEN_LIGHT_DETECTED'

STOPLINE_WAITING = 'STOPLINE_WAITING'


PEDESTRIAN_WAITING = 'PEDESTRIAN_WAITING'
PEDESTRIAN_CROSSED = 'PEDESTRIAN_CROSSED'

TRY_AVOID_ROADBLOCK = 'TRY_AVOID_ROADBLOCK'
IN_CONTINUE_LANE = 'IN_CONTINUE_LANE'
WAITING_OBSTACLE = 'WAITING_OBSTACLE'
OBSTACLE_GONE = 'OBSTACLE_GONE'
CAR_MOVING = 'CAR_MOVING'
CAR_STATIC = 'CAR_STATIC'
ULTRA_SOUND_EMERGENCY = 'ULTRA_SOUND_EMERGENCY'
ROADBLOCK_AVOIDING = 'ROADBLOCK_TRY_AVOID_ROADBLOCK'
CONTINUE_LANE_DRIVING = 'CONTINUE_LANE_DRIVING'
OBSTACLE_WAITING = 'OBSTACLE_WAITING'


SIGNAL_BLOCKED = 'SIGNAL_BLOCKED'
EVENT_TYPES = [
    ROADMAP_LOADED, OBSTACLE_DISTANCE_THRESHOLD, SIGNAL_DISTANCE_THRESHOLD, END_EVENT,
    STOP_LINE_DISTANCE_THRESHOLD, PARKING_SIGN_DETECTED, TRY_PARKING, CONTINUE_LANE_FOLLOWING,
    STOP_SIGN_DETECTED, STOP_WAITING, STOP_TIMEOUT, PARKING_COMPLETED, PEDESTRIAN_TIMEOUT, CAR_OVERTAKEN,
    ROADBLOCK_AVOIDED, IF_MOVING, IF_STATIC, CROSSWALK_SIGN_DETECTED, CROSSWALK_WAITING,
    END_OF_LOCAL_PATH, STOPLINE_TIMEOUT, SEMAPHORE_GREEN, HIGHWAY_ENTRY_SIGN_DETECTED, IN_HIGHWAY, PRIORITY_SIGN_DETECTED,
    ONE_WAY_SIGN_DETECTED,ROUNDABOUT_SIGN_DETECTED, NO_ENTRY_SIGN_DETECTED, PEDESTRIAN_DETECTED,
    CAR_DETECTED, ROADBLOCK_DETECTED, TRACKING_NODE, FINAL_NODE_REACHED,
    CROSSWALK_TIMEOUT, CROSSWALK_WAITING,RED_LIGHT_DETECTED,YELLOW_LIGHT_DETECTED, RED_LIGHT_WAITING, RED_LIGHT_FINISHED, YELLOW_LIGHT_WAITING,
    YELLOW_LIGHT_FINISHED, GREEN_LIGHT_DETECTED, STOPLINE_WAITING, PEDESTRIAN_WAITING, PEDESTRIAN_CROSSED, TRY_AVOID_ROADBLOCK,
    OBSTACLE_GONE, WAITING_OBSTACLE, INTERSECTION_STOP, INTERSECTION_PRIORITY_EVENT, ULTRA_SOUND_EMERGENCY, TRAFFIC_LIGHT_DETECTED,
    CAR_MOVING, CAR_STATIC, CONTINUE_LANE_DRIVING, OBSTACLE_WAITING,
    CONTINUE_ON_LANE, TRY_LEFT_PARKING, SIGNAL_BLOCKED, STOP_LINE_BLOCKED,
]

# ========================= SIGNS ==========================
STOP_SIGN = "Stop_sign"
PARKING_SIGN = "Parking_Sign"
CROSSWALK_SIGN = "Pedestrian_Sign"
PRIORITY_SIGN = "Priority_sign"
HIGHWAY_ENTRY_SIGN = "Motorway_start_sign"
HIGHWAY_END_SIGN = "Motorway_finish_sign"
ONE_WAY_SIGN = "One_Way_Sign"
ROUNDABOUT_SIGN = "Roundabout_sign"
NO_ENTRY_SIGN = "Deny_sign"

# ========================= OBSTACLES ==========================
PEDESTRIAN = "PEDESTRIAN"
CAR = "CAR"
ROADBLOCK = "ROADBLOCK"

# ========================= TRAFFIC LIGHT ==========================
RED = "RED"
YELLOW = "YELLOW"
GREEN = "GREEN"